Add Install Guide to repo.
cablelabs/snaps-kubernetes pull request #70
Opened 2018-06-14 16:44 UTC by chriscorcimiglia

#### What does this PR do?

Adds `install.md` to the repo (actually adds `doc` tree to repo which includes `install.md` and some figures). Fixes #56 

#### Do you have any concerns with this PR?

The guide needs to be tested. I simply converted the original document to Markdown.

Also, if changes are required, please feel free to make the changes to this branch. I will be out of the office next week and will not be able to take care of change requests. 

#### How can the reviewer verify this PR?

Review and execute the guide.

#### Any background context you want to provide?

No.

#### Screenshots or logs (if appropriate)

NA.

#### Questions:
- Have you connected this PR to the issue it resolves? **Yes.**
- Does the documentation need an update? **This does it.**
- Does this add new Python dependencies? **No.**
- Have you added unit or functional tests for this PR? **No.**
- Does this patch update any configuration files? **No.**

2018-06-14 16:55 UTC, spisarski requested changes
Clarify how to setup runtime and install snaps-kubernetes prior to running iaas_launch.py

2018-06-15 17:47 UTC, RandyLevensalor requested changes
Please move the images to the wiki or another file sharing site.  We don't want any binaries in our source repository.

2018-07-13 11:41 UTC, spisarski requested changes
I have 2 main issues:
1. Remove any references to the "sample config template" in snaps_k8s/k8s-deploy.yamle. This file should really never be used or altered
2. Streamline the build host setup. There isn't much other than python and sshpass (for which I'd like to see removed eventually) that is really necessary and ensure that the Python runtime is installed...

If you want to merge this now just to get it in, we can address my concerns later...

2018-07-13 18:40 UTC, markbridges approved these changes

2018-07-13 18:40 UTC, merged